### ISSUE TITLE
Making executeFemce dynamic creating multiple enter exit output for us.

### ISSUE THREAD

**Issue by nhardia1** [phulst/node-tile38#13]
withinSomeBounds = tileClient.withinQuery('reg_'+locationData.user_id).detect('enter','exit').bounds(sw_lat, sw_long, ne_lat, ne_long);
                    withinSomeBounds.executeFence((err, results) => {
                        if (err) {
                            console.error(err);
                        } else {
                            console.log(results);
                            if(results.detect == "enter"){
                                long = results.object.coordinates[0];
                                lat = results.object.coordinates[1];
                                user_id = results.id;
                                var message = {
                                    user_id: user_id,
                                    lat:lat,
                                    long:long,
                                    b:1
                                };
                                pub.publish('ch_'+locationData.user_id, JSON.stringify(message));
                            }
                        }
                    });

We are setting up multiple geofences but when set any lat long to them it returns multiple enter exit events.

**Comment by phulst** [comment]
This node library doesn't really create its own events, it just passes on events that it receives directly from the Tile38 server. So if you're receiving multiple enter or exit events when you shouldn't, that is most likely a Tile38 server issue. 

Can you try the same command using the Tile38 CLI and the WITHIN query? If you see the same thing then, you'll probably need to file an issue int he Tile38 project itself.

**Comment by nhardia1** [comment]
Ok thanks for update.
When i create **within  bound** with same fence name it create multiple instances so how could we stop that ?
we can user close function ofcourse but how we can destroy fence instance with particular fence name.

**Comment by phulst** [comment]
You should be able to follow this example: 
https://github.com/phulst/node-tile38/blob/master/examples/geofence.js
Each geofence will be its own instance and maintain its own socket to the server. If you call close() on it, that should close that particular fence/websocket but any others will stay open. 

(It would be nice if at some point multiple geofences could use the same websocket but that would require a more advanced communication protocol and isn't currently supported by Tile38 AFAIK. )
