### ISSUE TITLE
WHEREIN search option

### ISSUE THREAD

**Issue by srimaln91** [phulst/node-tile38#15]
It seems that the library does not support WHEREIN search option which is available for NEARBY, WITHIN, INTERSECTS, and SCAN commands.

**Comment by phulst** [comment]
Thanks for bringing this to my attention. I see that there's some new search options like WHEREIN, WHEREEVAL and CLIP that have been added more recently and which are not supported yet. I'll add support for them.

**Comment by phulst** [comment]
now fixed in version 0.6.7
