### ISSUE TITLE
Can U add some functionality?

### ISSUE THREAD

**Issue by geomen888** [phulst/node-tile38#17]
for example to 
1.client.nearbyQuery('fleet').roam('truck', 'orders', 3000) need to add also radius circle for 'orders' => client.nearbyQuery('fleet').roam('truck', 'orders', 3000, 10) 
OR something like this
2. client.set('fleet', "truck" + `${1}`, [lat, lng], { radius: 3000 } )
  client.set('fleet', "orders" + `${7}`, [lat, lng], { radius: 10 } )
 client.nearbyQuery('fleet').roam('truck', 'orders').output('radius')
, It's possible ???
Kind Regards 
Eugene.

**Comment by phulst** [comment]
According to the docs, the ROAM option only supports a key, pattern and single radius. If the Tile38 server doesn't support what you need, neither will this driver. You may need to submit a feature request with Tile38.
