### ISSUE TITLE
examples/search.js => client.withinQuery does not working for me

### ISSUE THREAD

**Issue by stavavram** [phulst/node-tile38#19]
Hi,
I tried to run client.withinQuery (on polygon) exactly like in search.js and i got the error:
message: "ERR wrong number of arguments for 'within' command"
stack: "ReplyError: ERR wrong number of arguments for 'within' command\n    at parseError (/home/stavav/projects/tile38-test/node_modules/redis-parser/lib/parser.js:193:12)\n    at parseType (/home/stavav/projects/tile38-test/node_modules/redis-parser/lib/parser.js:303:14)"

After that i checked the search.js and got the same error
i am working with tile38 1.17.1

thanks for help :)

**Comment by phulst** [comment]
I just updated to Tile server 1.17.4 and the search.js example still works fine for me. 
Can you try with 
```
node examples/search.js
```
and let me know your results? If this example works fine for you, perhaps you can update it to demonstrate the error, and share your branch, so I can reproduce it myself.

**Comment by phulst** [comment]
I still can't reproduce this and since I haven't heard back from you I'm closing this out.
