### ISSUE TITLE
Why do you require Babel transpiling?

### ISSUE THREAD

**Issue by emgeee** [phulst/node-tile38#2]
All of the ES2015 features this library takes advantage of are natively supported as of Node v6, just wondering why you're requiring the extra tranpilation step.

**Comment by phulst** [comment]
I didn't transpile at first, but got a 'complaint' that this library wouldn't run with Node 4 LTS versions. Turned out to be fairly easy to support that, so I figured why not...

**Comment by emgeee** [comment]
Thanks for the response! I'm finding that developing this library and with this library is made more difficult by the transpilation step as I can't easily install the dependency from a github repo.

**Comment by phulst** [comment]
There was a different issue related to the npm packaging which I resolved recently. You should be able to just pull the latest version 0.6.2 with npm. I am planning on doing patch releases any time I've added something potentially useful to anyone, so there's probably no need to refer directly to the github repo when pulling in the tile38 library.

**Comment by emgeee** [comment]
That's fair, I was trying to use my forked repo as a dependency while waiting for my PR to be merged.
