### ISSUE TITLE
Please Support Configurable Error function

### ISSUE THREAD

**Issue by KrishnaPG** [phulst/node-tile38#21]
Thank you for sharing this good work. It is helpful. One suggestion.

Please accept a err function as parameter, so that we can configure which logger should be used. Currently `on error` code is hard coded to use console.
https://github.com/phulst/node-tile38/blob/7b122c55932be24610612b1b364512ca58346c10/src/tile38.js#L21

#### suggestion
Please do something like below:
````
const defaultErrHandler = err =>console.error('Tile38 connection error: ' + err);

constructor({port, host, password, debug = false} = {}, onErr = defaultErrHandler ) {
    // ....
    this.client.on('error', onErr);
}
````

Similarly, replace the debug code: https://github.com/phulst/node-tile38/blob/7b122c55932be24610612b1b364512ca58346c10/src/tile38.js#L41-L43

with something as below:
````
 if (this.debug) this.debugLog(`sending command "${cmd} ${args.join(' ')}"`); 
````

The `debugLog` callback can be accepted as parameter to the constructor, or set equal to the `onErr` in the constructor (though it is strongly advised to keep both separate).

````
const defaultDebugHandler = msg =>console.log(msg);

constructor({port, host, password, debug = false} = {}, onErr = defaultErrHandler, debugLogFn = defaultDebugLog ) {
   // ...
   this.debugLog = debugLogFn;
}
````

Implementing this kind of `inversion of control` design pattern makes this package play more nicely with other modules when used in large scale projects.

**Comment by phulst** [comment]
Thanks for your suggestion. I've made some simple (backwards compatible) changes that will allow you to pass in a custom logger. You can now call the Tile38 constructor as follows: 
```
const myLogger = {
   log: function(msg) { ... },
   warn: function(msg) { ... },
   error: function(msg) { ... }
}
const tile38 = new Tile38({ debug: true, logger: myLogger });
```
essentially the interface should be the same as that of the built-in console object. 
The 'debug' property works as before. If not set (or set to false), only the warn or error messages will be logged.

**Comment by KrishnaPG** [comment]
Thanks. That will be helpful.
