### ISSUE TITLE
SERVER command responding with Array (JSON.Parse() failing on it) after network reconnection 

### ISSUE THREAD

**Issue by KrishnaPG** [phulst/node-tile38#22]
Most probably this is `tile38` server issue - but just in case if this is related to any configuration (such as requesting the output format properly from the server etc.), posting here too.

The server command works fine usually (resulting in a valid JSON). However, started observing an issue when network connection is lost to the server, and the server command is queued and then network connection is restored. Afterwards, it starts giving below response:
````
sending command "SERVER "                                              tile38.js:62
Array(40) ["aof_size", "345637", "avg_item_size", "178955", "cpus", "4", "heap_released", "62750720", …]             tile38.js:69
````
which started to fail with JSON.parse()

The key, and values are returned as elements of an array side-by-side, instead of as key-value pairs of an object.

FWIW, the response is coming with type 42 in the redis-parser\lib\parser.js file (Screenshot below):
![image](https://user-images.githubusercontent.com/4610831/60705043-bb815d80-9f23-11e9-8975-971ff2d736c8.png)

**Comment by KrishnaPG** [comment]
I have checked and confirmed that this is not issue with the server.  In the constructor the output format is being set to JSON : https://github.com/phulst/node-tile38/blob/7b122c55932be24610612b1b364512ca58346c10/src/tile38.js#L24

However, this seem to be disappearing when network is disconnected and reConnected. 

#### Fix:
Change the line to as below:
````
this.client.on('connect', () => this.sendCommand('OUTPUT', null, 'json'));
````
This sets the output properly whenever connection is re-established.

**Comment by KrishnaPG** [comment]
Sent PR: https://github.com/phulst/node-tile38/pull/23

**Comment by phulst** [comment]
thanks for the bug report and PR. Fix is in master now, I will do a version update soon.
