### ISSUE TITLE
close() does not work on fence queries

### ISSUE THREAD

**Issue by saltatory** [phulst/node-tile38#25]
When I 

```
console.log(Object.getOwnPropertyNames(this.userResultsFence));
```

I get 

```
[ 'debug', 'socket' ]
```

Note: there is no close method present.

Thus when I call close on the fence, nothing happens.

However, if I instead call 

```
this.userResultsFence.socket.destroy();
```

This successfully closes the handle. I see this in node because I am exporting the nodejs_active_handles prometheus metric and only this reduces the handle count on close.

**Comment by phulst** [comment]
can you compare your code against the example here: 

https://github.com/phulst/node-tile38/blob/master/examples/geofence.js

I believe in the above example the close() works just fine...

**Comment by saltatory** [comment]
You are correct. Sorry for the confusion.

FWIW - I had a load test client generating a large number of connections. When the load test client was killed (Ctrl+C), it did not call the logic to close down the Tile38 connection as I thought it was.

Thanks again!

**Comment by phulst** [comment]
ok thanks. Would be interested in your load test results. I haven't done any load testing on this node library (or on Tile38 in general for that matter), but would be interested to find out how many concurrent connections (and live geofences) it can support. If you find any bottlenecks in this library definitely let me know!
