### ISSUE TITLE
Feature Request: object.geojson

### ISSUE THREAD

**Issue by dBitech** [phulst/node-tile38#26]
Helper method (or examples) to take the objects returned from the queries such as within, intersects and have them return properly formatted geojson.

**Comment by dBitech** [comment]
I cludged together a simple viewer, 
https://github.com/dBitech/tile38-js-api

**Comment by phulst** [comment]
thanks for your suggestion. I looked at some code and thought about this for a bit but I think it's best if this library makes a minimal amount of assumptions on what the responses from Tile38 should look like, and not try to interpret or convert the response body. 
It would make this library more fragile (things could break if Tile38 server changes response formats in future updates). 
Looking at the output from the server when running examples/search.js I see some things that would make parsing to GeoJSON more complete. For example, if you use WITHIN with a set of bounds, an event from the server might look like this: 

```
{"command":"set","group":"618b6c01d5861cc084712b26","detect":"enter","key":"eastbay","time":"2021-11-09T22:51:45.351141-08:00","id":"user4","point":{"lat":37.83322432396937,"lon":-122.22461761836865}}
```

If you use WITHIN and specify a geojson object to set the bounds (ie pass in a polygon geojson), an event may look like this: 

```
{"command":"set","group":"618b6bf5d5861cc084712b23","detect":"exit","key":"eastbay","time":"2021-11-09T22:51:49.354696-08:00","id":"user8","object":{"type":"Point","coordinates":[-122.24572626404643,37.81928762005495]}}
```

You can see that in the latter event the response already includes geojson, so it appears that if you pass a geojson object to set your fences, the events you receive will also include geojson. 

If that's not enough, you could try to use the GeoJSON node library to parse the response. For example, the latter response could be parsed like this: 
```
let geo = GeoJSON.parse(results, {GeoJSON: 'object'});
```
and would then produce an object that looks like this: 
```
{
  type: 'Feature',
  geometry: {
    type: 'Point',
    coordinates: [ -122.24572626404643, 37.81928762005495 ]
  },
  properties: {
    command: 'set',
    group: '618b6bf5d5861cc084712b23',
    detect: 'exit',
    key: 'eastbay',
    time: '2021-11-09T22:51:49.354696-08:00',
    id: 'user8'
  }
}
```

Which may or may not be what you want.  As I said, I don't think this type of conversion functionality should live in this library/or driver. If you need more 'proper' geojson objects, I suggest taking a look at [geojson](https://github.com/caseycesari/geojson.js) which can make the conversion fairly trivial depending on your needs.
