### ISSUE TITLE
Tile38 connection error

### ISSUE THREAD

**Issue by mjc4thewin** [phulst/node-tile38#29]
I've got a docker-compose.yaml see below, that is spinning up Tile38 and a node/express api.  First thing I'm trying to do is use node-tile to connect to the Tile38 container.  My plan is to build a REST API to sit in front of Tile.  

The node service spins up fine, but when I try to connect to Tile like this: 
`const Tile38 = require('tile38');
const tileClient = new Tile38({host: '0.0.0.0', port: 9851, debug: true });`

I get this error: 
`Running on http://0.0.0.0:3000
Tile38 connection error: Error: Redis connection to localhost:9851 failed - connect ECONNREFUSED 127.0.0.1:9851
Tile38 connection error: Error: Redis connection to localhost:9851 failed - connect ECONNREFUSED 127.0.0.1:9851
Tile38 connection error: Error: Redis connection to localhost:9851 failed - connect ECONNREFUSED 127.0.0.1:9851
Tile38 connection error: Error: Redis connection to localhost:9851 failed - connect ECONNREFUSED 127.0.0.1:9851
Tile38 connection error: Error: Redis connection to localhost:9851 failed - connect ECONNREFUSED 127.0.0.1:9851
Tile38 connection error: Error: Redis connection to localhost:9851 failed - connect ECONNREFUSED 127.0.0.1:9851
Tile38 connection error: Error: Redis connection to localhost:9851 failed - connect ECONNREFUSED 127.0.0.1:9851
Tile38 connection error: Error: Redis connection to localhost:9851 failed - connect ECONNREFUSED 127.0.0.1:9851`

Here's my Docker-compose.yaml
`version: '3'
services:
  tile38:
    image: "tile38/tile38"
    ports:
     - "9851:9851"
  webapi:
    build: .
    image: "node-tile38:1.7"
    ports:
     - "49160:3000"
    links:
     - tile38`

**Comment by mjc4thewin** [comment]
I tried telnet and getting connection errors too...

telnet localhost 9851
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host

**Comment by Aldiwildan77** [comment]
it connected if we run the tile38 using docker run, Idk why I have got the problem same with you

**Comment by Aldiwildan77** [comment]
@zRealMikeJordan try to adding `depends_on: - tile38` in webapi service inside the docker-compose file.

**Comment by phulst** [comment]
I'm assuming you've resolved this by now... pretty sure it must have been an issue with the configuration of your container.
