### ISSUE TITLE
Dependency warning

### ISSUE THREAD

**Issue by rafasad** [phulst/node-tile38#33]
Hi,
Using the lib, these warnings never appeared, but now it started to appear. 
I am passing all parameters correctly and works. But keep giving the version warnings!

`node_redis: Deprecated: The JSET command contains a "null" argument.
This is converted to a "null" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.`

**Comment by phulst** [comment]
Can you share how you are calling jset? are you calling jset with an explicit null value? Like this: 

```
tile38.jset('user', '100', 'attr.name', null)
```

that's the only way I can reproduce this issue. If so, could you use jdel instead? the jset() function requires 4 arguments and I don't think any can be null or omitted.

**Comment by phulst** [comment]
closing this issue, nothing to fix
