### ISSUE TITLE
Exit point not detecting when the vehicle leave the fence and getting 2 enter callbacks

### ISSUE THREAD

**Issue by narru033** [phulst/node-tile38#40]
Hi, I'm using the below example. It triggered only enter event not getting the exit event but the exit point also present.

```
let query = client.intersectsQuery('fleet').detect('enter','exit').circle(43.686, -114.367, 100)

// start the live geofence
let fence = query.executeFence((err, results) => {
  // this callback will be called multiple times
  if (err) {
    console.log("error: " + err);
  } else {
    console.dir(results);
  }
});

// set a coordinate
client.set('fleet', 'truck1', [43.6855, -114.36803]); // Detect as enter
client.set('fleet', 'truck2', [43.68579, -114.367]); // Detect as enter
client.set('fleet', 'truck3', [43.68507, -114.36746]); // Not detected
client.set('fleet', 'truck4', [43.68192, -114.36595]); // Not detected
```

tried the above example. Please suggest me

**Comment by tk120404** [comment]
@narru033  exit is not detected as the fleets are marked as truck3 and truck4 . Pls set it as truck1 and truck2 to detect the exits
// set a coordinate
client.set('fleet', 'truck1', [43.6855, -114.36803]); // Detect as enter
client.set('fleet', 'truck2', [43.68579, -114.367]); // Detect as enter
client.set('fleet', 'truck1', [43.68507, -114.36746]); // will detect as exit
client.set('fleet', 'truck2', [43.68192, -114.36595]); // will detect as exit

**Comment by phulst** [comment]
agree with @tk120404 above - his suggestion should resolve this for you. Closing this issue.
