### ISSUE TITLE
Set JSON object to tile38

### ISSUE THREAD

**Issue by RilusMahmud** [phulst/node-tile38#41]
While setting JSON object to tile38 with client.set, the coordinates are set as NaN, why and how to set JSON object to tile38.
But I've done that with python, then it works fine.
Please help!

**Comment by tk120404** [comment]
@RilusMahmud Pls share your jsonobject structure or the whole command here

**Comment by phulst** [comment]
Since @RilusMahmud never responded I'm closing this issue. All the ways to use the set command are pretty well documented in the readme, and I suspect it was called incorrectly.
