### ISSUE TITLE
no changes from release 0.9.0 and 0.8.0

### ISSUE THREAD

**Issue by atmosferia-projects** [phulst/node-tile38#46]
Hi @phulst thanks for your great job! We think we have hit a problem with your latest release (0.9.0)

0.9.0 claims to solve problems with executeCommand, but once installed (with npm) we cannot see any reference to executeCommand in tile38.js. But in your repo ( branch 0.9.0), clearly exists ( tile 38.js line 51). After scraching our heads and taking a look to the npmjs repo, we have compared your github release 0.8.0 with 0.9.0 and both seems to have the same code.
May be you created release 0.9.0 with the 0.8.0 branch or code? 

Can you recreate it with the latest changes or create a new release 0.9.1 ?

Thanks!

TIA

**Comment by atmosferia-projects** [comment]
After a deeper look, may be the executeCommand was available in 0.8.0 and you took it off in 0.9.0 ?

**Comment by phulst** [comment]
hm.. let me take a look and get back to you

**Comment by atmosferia-projects** [comment]
Thanks, @phulst !

=================  FALSE ======================
We don't have very clear what's happening, the only thing clear to us is:

Source code on 0.9.0 release has not 

`    executeCommand(command, opts = {}) {
        let returnProp = opts.returnProp || 'ok';
        let parseJson = (opts.parseJson === undefined) ? true : opts.parseJson; // could be set as false
        let opt = parseJson ? returnProp : false;
        let commandArr = command.split(' ');
        return this.sendCommand(commandArr.shift(), opt, commandArr);`

in the other hand, code in repo tag 0.9.0 has this code
=================  FALSE ======================

Update:

executeCommand exists in release  0.9.0 source code but doesn't exists in the npmjs 0.9.0 distribution

Steps to reproduce:

We force node-tile38 to be version 0.9.0 in our package.json
`**desarrollador@vmi385490: grep tile package.json

  "name": "api-tramas-tile38",
    "tile38",
    "tile38": "^0.9.0",

desarrollador@vmi385490**`

If we inspect node_modules/tile38/dist/tile38.js after npm install, the code about executecommand doesn't exists


`**desarrollador@vmi385490:$ grep -i executeCommand  node_modules/tile38/dist/tile38.js

desarrollador@vmi385490:$**`


but changelog show us that we are effectively using the code from 0.9.0

`**desarrollador@vmi385490:$ grep "======" -A4 -B1 node_modules/tile38CHANGELOG.md

Revision history:

0.9.0 / November 29, 2021
   fixed bug in chaining of options
   fixed issues with new executeCommand function

desarrollador@vmi385490:$**`

Have it sense to you?
😶

**Comment by atmosferia-projects** [comment]
Hi @phulst 

Any news?

thanks

**Comment by phulst** [comment]
I pushed a new version v0.9.1 to correct this. Can you let me know if you see the changes now? thanks

**Comment by arnabb1swas** [comment]
@phulst no buddy it's still missing in the package

**Comment by phulst** [comment]
Finally took some time to figure this out and pushed a new version v0.9.3 that resolves these issues.
