### ISSUE TITLE
How would you use limit with nearby query with no radius ?

### ISSUE THREAD

**Issue by py4object** [phulst/node-tile38#5]
Something like :
NEARBY fleet LIMIT 1 POINT 33.462 -112.268

**Comment by phulst** [comment]
The library previously didn't support that but I've made the radius optional now (in version 0.6.6). 
If you execute the query as follows: 
```
client.nearbyQuery('fleet').point(33.1212, -122.2423).limit(1).execute();
```
It will send the following command to the server: 
```
NEARBY fleet LIMIT 1 POINT 33.1212 -122.2423
```
