### ISSUE TITLE
support urls?

### ISSUE THREAD

**Issue by yocontra** [phulst/node-tile38#9]
it would be great if this module just took the constructor args and passed them straight through, so we could use URLs instead of host/port. this makes it much easier to provide this info via env vars.

**Comment by phulst** [comment]
Thanks for your suggestion. 
The redis library that is used to connect to Tile38 supports a number of elements in the connection URL but it's not clear which would actually be supported by Tile38. There are no database names or numbers, no additional options (that I'm aware of) and there isn't even the concept of a username. 

Hence the connection URL would have to simply look something like 'password@hostname:port'. 
I don't think there's much value in implementing until there's greater complexity (and Tile38 actually supports user accounts).

I did add support for environment variables TILE38_HOST, TILE38_PORT and TILE38_PASSWD so you can authenticate and have additional options for making your connection settings configurable.
